### ISSUE TITLE
Certain torrents return "-1" for seeders and leechers.

### ISSUE THREAD

**Issue by lewisgoddard** [eustasy/phoenix#12]
More info to come.

**Comment by enebe-nb** [comment]
This can be from last commit sql changes, or from database update.
Waiting for more info.

**Comment by lewisgoddard** [comment]
This has been happening for a while, but is a little difficult too debug. I'm going to test some torrents over the next few days.

**Comment by enebe-nb** [comment]
Sometimes the tracker answer with 'Could not set last maintenance time.'
While cleaning idle peers the tracker access an unexistent column in 'tasks' table, (maybe it exists in one of other projects).
Isn't this related to the problem?

**Comment by lewisgoddard** [comment]
The database:
```
	$result = mysqli_query($connection,
		'CREATE TABLE IF NOT EXISTS `'.$settings['db_prefix'].'tasks` (' .
			'`name` varchar(5) NOT NULL,' .
			'`value` int(10) unsigned NOT NULL' .
		') ENGINE=MyISAM DEFAULT CHARSET=latin1'
	);
```

The task:
```
$task = mysqli_query('REPLACE INTO `'.$settings['db_prefix'].'tasks` (`prune`) VALUES (\''.$time.'\')');
```

I think that task is supposed to be:
```
$task = mysqli_query('REPLACE INTO `'.$settings['db_prefix'].'tasks` (`name`, `value`) VALUES (\'prune\', \''.$time.'\')');
```

That could well be the problem. Once I am home I will check if that has ever run successfully.
