### ISSUE TITLE
Document how to set up cron jobs in README.md [$25]

### ISSUE THREAD

**Issue by lewisgoddard** [eustasy/phoenix#28]
Steps for configuring cron should go under a h3 header titled "Cron", immediately after the current Configuration section. Should be in a list-format to match the Installation section. Try to keep things as simple as possible, and maybe don't run both cron jobs at once, delay the backup for a couple of minutes. Always give root-relative file names in backticks, along with any code that needs changing. Make sure all code blocks are clearly labeled _before_ they occur.

- [x] Configure `_cron/hourly/backup-database.sh` (path, username, password, database)
- [x] Configure for `_cron/hourly/clean-and-optimize.php`
- [x] Example crontab.
- [x] Disable cleaning in requests.

**Comment by dogsAreReallyCool** [comment]
[final solution](https://github.com/dogsAreReallyCool/phoenix/blob/ce56bfcc53ebbb3083f1febd7610c7e5cbb7d559/README.md)

**Comment by lewisgoddard** [comment]
This issue is no longer in progress.
